# Generated by Django 4.2.1 on 2023-06-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
