# Generated by Django 4.2.1 on 2023-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_profile_last_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
